### ISSUE TITLE
feat: option to trigger command on startup

### ISSUE THREAD

**Issue by privatenumber** [lukeed/watchlist#11]
## Problem
I'd like for the command to run as I start the watch eg. running a test.

Currently, I have to trigger a blank save to make it run.

## Feature request
An `-i, --initial` or `--leading` flag (like lodash's debounce), to invoke the command on startup.

**Comment by cometkim** [comment]
> eg. running a test.

I'm using `{command} || true && watchlist {...files} -- {command}` for this.
