### ISSUE TITLE
Differences between Watchlist and fabiospampinato/watcher

### ISSUE THREAD

**Issue by paulocoghi** [lukeed/watchlist#15]
Hello Luke! Nice to see you again!

I would like to ask what would be the differences between Watchlist and [fabiospampinato/watcher](https://github.com/fabiospampinato/watcher).

Thank you again!

**Comment by lukeed** [comment]
Hey :) 

Not sure tbh, never used it. On initial pass, it seems like it handles symlinks and has configurable polling support. Watchlist uses `fs.watch` directly (I wrap it so it's reliable cross platform), which doesn't poll & I don't deal with symlinks. I imagine mine is faster cuz it uses whatever native stuff Node is doing & it's less deps.

CLI usage seems to be different too.

I'm sure it's great, but I put this together cuz people were asking for a solution for uvu and `watchlist src tests -- uvu tests` felt nice to me.

Hope that helps~
